[package]
name = "rgetty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam = "0.7.0"
chrono = "0.4.19"
libc = "0.2.121"